version: '2.4'
services:
  mysql:
    container_name: quiz-mysql
    ports:
      - "3306:3306"
    extends:
        file: build/docker-compose.common.yml
        service: mysql
  # postgres:
  #   container_name: mattermost-postgres
  #   ports:
  #     - "5432:5432"
  #   extends:
  #       file: build/docker-compose.common.yml
  #       service: postgres
  minio:
    container_name: quiz-minio
    ports:
      - "9000:9000"
    extends:
        file: build/docker-compose.common.yml
        service: minio
  inbucket:
    container_name: quiz-inbucket
    ports:
      - "10025:10025"
      - "10080:10080"
      - "10110:10110"
    extends:
        file: build/docker-compose.common.yml
        service: inbucket
  openldap:
    container_name: quiz-openldap
    ports:
      - "389:389"
      - "636:636"
    extends:
        file: build/docker-compose.common.yml
        service: openldap
  elasticsearch:
    container_name: quiz-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    extends:
        file: build/docker-compose.common.yml
        service: elasticsearch
  start_dependencies:
    image: mattermost/mattermost-wait-for-dep:latest
    networks:
      - q-test
    depends_on:
      - mysql
      # - postgres
      - minio
      - inbucket
      - openldap
      - elasticsearch
    command: mysql:3306 minio:9000 inbucket:10080 openldap:389 elasticsearch:9200

networks:
  q-test:
    driver: bridge
